language: node_js
node_js:
- '0.12'
notifications:
  email: false
  slack:
    secure: OjiU/3vGWgqgHcerW1EvH5VEJItjaXva1/2LmuMHMnCgz69uNfQvyGtYfFttvjqXFTjtFl+KfyYs36KJfWpQe6pNY3ieAPAT+e9g4QObAtf7Sg9kf/lcFYawEi+iM/nhkIMUqU1GRbyi+yDBPZPMQZbaVXFAMG7FdoXT1umT2Tg=
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && npm run deploy
env:
  global:
    secure: RTVJzrZvJwbyfr9KyvNXy9nN/P9NGHAheiUovpbh7OjtJOd+kPK/97zTQ8Ud64mRNdPVzlR1B9fNE0ABq1j7MtKXTPITscHLLLaVYCc6rcXPUWnVjH3/1BtoXrmNCYMEyKie3HITHrnCHogWok9C4nYVbEp6BK/B71KrFT1tU6o=
cache:
  directories:
  - node_modules
sudo: false
